name: Terraform Apply
#Only Run this worklfow on commits to the main branch:
permissions:
  id-token: write

on:
  push:
    branches:
      - 'main'
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          # Specify the IAM role to assume here
          role-to-assume: arn:aws:iam::980308885448:role/github-actions-oidc20230321183457034600000001 
          aws-region: eu-west-2
        
      # Run Terraform using Hashicorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v1
        with: 
          terraform_version: 1.3.9
          terraform_wrapper: false

      - run: |
          terraform init
          terraform apply --auto-approve
      

